name: Jira Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  jira-check:
    uses: narendarkumar4944-blip/org-devops-workflows/.github/workflows/jira-check.yml@nks1
    secrets: inherit
